version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: geo_search_db
    restart: always
    environment:
      POSTGRES_DB: geo_search
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: geo_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: